POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "tester",
    "author": "daniel",
    "url": "ablog",
    "likes": 7

}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/60f6be03f0d3f04f386c5ca1

###
PUT http://localhost:3003/api/blogs/60e81d61982aea34884d7d3a
Content-Type: application/json

{
    "likes": 56
}