POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "another test",
    "author": "daniel",
    "url": "yblog",
    "likes": 7,
    "userId": "60f6d1e9f8ae904a481a672d"
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/60f6be03f0d3f04f386c5ca1

###
PUT http://localhost:3003/api/blogs/60e81d61982aea34884d7d3a
Content-Type: application/json

{
    "likes": 56
}