POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "first blog post",
    "author": "daniel",
    "url": "firstblog",
    "likes": 7

}

###
GET http://localhost:3003/api/blogs